import Link from 'next/link'

export const metadata = {
  title: 'Terms of Service — Tapr',
  description: 'The terms and conditions governing your use of Tapr.',
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0A1628]">
      <div className="max-w-3xl mx-auto px-6 py-16">
        <Link
          href="/"
          className="inline-flex items-center gap-1.5 text-[#6B7280] hover:text-white text-sm transition-colors mb-10"
        >
          ← Back to Tapr
        </Link>

        <h1 className="font-display text-5xl text-white mb-2">TERMS OF SERVICE</h1>
        <p className="text-[#6B7280] text-sm mb-12">Last updated: May 2, 2025</p>

        <div className="prose prose-invert max-w-none space-y-10 text-[#D1D5DB] leading-relaxed">

          <section>
            <h2 className="font-display text-2xl text-white mb-3">AGREEMENT</h2>
            <p>
              These Terms of Service (&ldquo;Terms&rdquo;) govern your access to and use of the Tapr platform
              operated by Tapr, LLC, a North Carolina limited liability company (&ldquo;Tapr,&rdquo;
              &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;). By creating an account or using Tapr,
              you agree to these Terms. If you do not agree, do not use the service.
            </p>
          </section>

          <section>
            <h2 className="font-display text-2xl text-white mb-3">THE SERVICE</h2>
            <p>
              Tapr is a personalized endurance sports gear recommendation platform. We combine your athlete profile
              with aggregated review data and AI analysis to suggest gear that may suit your specific needs,
              body dimensions, race goals, and budget.
            </p>
          </section>

          <section>
            <h2 className="font-display text-2xl text-white mb-3">IMPORTANT: AI RECOMMENDATIONS DISCLAIMER</h2>
            <div className="bg-[#FF6B3510] border border-[#FF6B3530] rounded-lg p-5">
              <p className="text-white">
                Tapr&apos;s recommendations are generated by artificial intelligence and are provided
                for <strong>informational purposes only</strong>. They do not constitute professional advice
                of any kind — including but not limited to medical, fitness, or financial advice.
              </p>
              <p className="mt-3">
                Gear recommendations are based on publicly available review data, manufacturer specifications,
                and the profile information you provide. Tapr does not independently test products. Actual
                product performance, fit, availability, and pricing may differ from what is described.
                You are solely responsible for verifying that any gear you purchase is appropriate for your
                body, fitness level, and intended use before purchasing or racing with it.
              </p>
              <p className="mt-3">
                <strong>If you have any physical condition, injury, or health concern that may affect gear
                selection, consult a qualified medical or fitness professional before making purchasing
                decisions.</strong>
              </p>
            </div>
          </section>

          <section>
            <h2 className="font-display text-2xl text-white mb-3">ACCOUNTS</h2>
            <p>
              You must be at least 13 years old to create an account. You are responsible for maintaining
              the confidentiality of your login credentials and for all activity that occurs under your account.
              Notify us immediately at{' '}
              <Link href="/contact" className="text-[#FF6B35] hover:underline">contact us</Link>{' '}
              if you suspect unauthorized access.
            </p>
            <p className="mt-3">
              You agree to provide accurate profile information. Inaccurate profile data will produce
              less relevant recommendations — Tapr is not responsible for recommendations based on
              information you provide incorrectly.
            </p>
          </section>

          <section>
            <h2 className="font-display text-2xl text-white mb-3">CREDITS AND BILLING</h2>

            <h3 className="text-white font-semibold mt-5 mb-2">Free Credits</h3>
            <p>
              New accounts receive 3 free credits upon signup. Free credits do not expire and can be used
              for any recommendation or comparison. No credit card is required to use free credits.
            </p>

            <h3 className="text-white font-semibold mt-5 mb-2">Credit Packs</h3>
            <p>
              Additional credits are available for purchase in packs: 3 credits for $2.99, 10 credits for
              $8.99, and 25 credits for $17.99. Credit packs are one-time purchases — there are no
              subscriptions or recurring charges. Pricing may change; the price at time of purchase applies.
            </p>

            <h3 className="text-white font-semibold mt-5 mb-2">Billing</h3>
            <p>
              Credit pack purchases are processed through Stripe. Credits are added to your account
              immediately upon payment confirmation.
            </p>

            <h3 className="text-white font-semibold mt-5 mb-2">Refunds</h3>
            <p>
              Credits are non-refundable once purchased, except where required by applicable law. If you
              believe you were charged in error, contact us at{' '}
              <a href="mailto:hello@taprai.com" className="text-[#FF6B35] hover:underline">hello@taprai.com</a>{' '}
              and we will review it.
            </p>
          </section>

          <section>
            <h2 className="font-display text-2xl text-white mb-3">AFFILIATE RELATIONSHIPS</h2>
            <p>
              Tapr earns affiliate commissions when you purchase products through links on our platform.
              This is how we fund the service alongside credit pack purchases.
            </p>
            <p className="mt-3">
              Our affiliate relationships do not influence which products we recommend. Recommendations are
              determined entirely by fit to your athlete profile, review data, and product performance.
              We do not accept payment from gear brands to influence rankings.
            </p>
            <p className="mt-3">
              All affiliate links are routed through our servers before redirecting to retailers. We log
              clicks for commission attribution. Retailers may set their own tracking cookies after you
              arrive on their site.
            </p>
          </section>

          <section>
            <h2 className="font-display text-2xl text-white mb-3">ACCEPTABLE USE</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Use Tapr for any unlawful purpose</li>
              <li>Attempt to circumvent usage limits or account restrictions</li>
              <li>Scrape, crawl, or systematically extract content or data from Tapr</li>
              <li>Use automated tools to generate recommendations at scale</li>
              <li>Impersonate another person or entity</li>
              <li>Interfere with the security or integrity of the service</li>
              <li>Resell or redistribute Tapr recommendations or content without permission</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-2xl text-white mb-3">INTELLECTUAL PROPERTY</h2>
            <p>
              The Tapr platform, including its design, code, brand, and the structure of its AI prompts and
              recommendation methodology, is owned by Tapr, LLC. Nothing in these Terms grants you any
              right to use our trademarks, logos, or proprietary content without our written permission.
            </p>
            <p className="mt-3">
              The recommendations we generate are based in part on your personal profile data. You may use
              your own recommendations for personal purchasing decisions. You may not publish, resell, or
              redistribute AI-generated recommendation content at scale.
            </p>
          </section>

          <section>
            <h2 className="font-display text-2xl text-white mb-3">DISCLAIMER OF WARRANTIES</h2>
            <p className="uppercase text-sm tracking-wide">
              Tapr is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties of any kind,
              either express or implied. We do not warrant that the service will be uninterrupted, error-free,
              or free of viruses. We do not warrant the accuracy, completeness, or fitness for a particular
              purpose of any recommendation, product description, price, or availability information on
              the platform.
            </p>
            <p className="mt-3 uppercase text-sm tracking-wide">
              Product prices shown on Tapr are approximate and sourced from publicly available data.
              Actual prices at retailers may differ. Always verify current pricing before purchasing.
            </p>
          </section>

          <section>
            <h2 className="font-display text-2xl text-white mb-3">LIMITATION OF LIABILITY</h2>
            <p className="uppercase text-sm tracking-wide">
              To the fullest extent permitted by law, Tapr, LLC and its officers, members, employees, and
              agents will not be liable for any indirect, incidental, special, consequential, or punitive
              damages — including but not limited to loss of profits, data, or goodwill — arising out of
              or related to your use of the service, even if we have been advised of the possibility of
              such damages.
            </p>
            <p className="mt-3 uppercase text-sm tracking-wide">
              Our total liability to you for any claim arising from these Terms or your use of Tapr will
              not exceed the greater of (a) the amount you paid us in the 12 months preceding the claim,
              or (b) $50.
            </p>
          </section>

          <section>
            <h2 className="font-display text-2xl text-white mb-3">INDEMNIFICATION</h2>
            <p>
              You agree to indemnify and hold harmless Tapr, LLC and its officers, members, employees,
              and agents from any claims, damages, losses, or expenses (including reasonable legal fees)
              arising from your use of the service, your violation of these Terms, or your violation of
              any third-party rights.
            </p>
          </section>

          <section>
            <h2 className="font-display text-2xl text-white mb-3">TERMINATION</h2>
            <p>
              We reserve the right to suspend or terminate your account at any time for violation of
              these Terms, fraudulent activity, or behavior that harms other users or the platform.
              If your account is terminated for cause, you are not entitled to a refund of any credits
              purchased.
            </p>
            <p className="mt-3">
              You may delete your account at any time. Upon deletion, we will remove your personal data
              as described in our <Link href="/privacy" className="text-[#FF6B35] hover:underline">Privacy Policy</Link>.
            </p>
          </section>

          <section>
            <h2 className="font-display text-2xl text-white mb-3">CHANGES TO THESE TERMS</h2>
            <p>
              We may update these Terms as the service evolves. Material changes will be communicated by
              email or in-app notice at least 14 days before taking effect. Continued use of Tapr after
              changes take effect constitutes your acceptance of the updated Terms.
            </p>
          </section>

          <section>
            <h2 className="font-display text-2xl text-white mb-3">GOVERNING LAW AND DISPUTES</h2>
            <p>
              These Terms are governed by the laws of the State of North Carolina, without regard to
              conflict of law principles. Any disputes arising under these Terms will be resolved in the
              state or federal courts located in North Carolina, and you consent to personal jurisdiction
              in those courts.
            </p>
          </section>

          <section>
            <h2 className="font-display text-2xl text-white mb-3">CONTACT</h2>
            <p>
              Tapr, LLC<br />
              North Carolina, United States<br />
              <Link href="/contact" className="text-[#FF6B35] hover:underline">contact us</Link>
            </p>
          </section>

        </div>
      </div>
    </div>
  )
}
